<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-4BCRE3U" failures="1" tests="3" name="Test" time="11.549" errors="0" timestamp="2022-05-26T12:33:16 IST">
  <testcase classname="com.sdet.AppTest" name="testlogin1" time="0.016"/>
  <testcase classname="com.sdet.AppTest" name="testlogin2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at com.sdet.AppTest.testlogin2(AppTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testlogin2 -->
  <testcase classname="com.sdet.TC_Login" name="login_Test" time="11.477"/>
</testsuite> <!-- Test -->
